### PR TITLE
basic TravisCI integration

### PR DESCRIPTION
**Pull request by thraxil**
Just run flake8 on the repo for now. Mostly this is to get some integration in place and make sure it's configured and working properly. Next we can add tests and automated PyPI deployment, etc.

### CODE REVIEW

**Comment by thraxil** [comment]
I added one pass to fix whitespace-related errors that flake8 flags. There are still failures, so Travis shows it as having failed checks. But fixing the rest should be done in a separate PR once this one is in so the fixes can more easily be reviewed.

**Comment by iamjazzar** [comment]
🎉🎉🎉🎉

**Comment by iamjazzar** [comment]
This is a good step forward! Thanks @thraxil.

**Review by iamjazzar — APPROVED** [review]

**Review by thatguynishant — APPROVED** [review]
@thraxil looks good

**Pull request merged**
